const LOGIN = "LOGIN"
const LOGOUT = "LOGOUT"
const GET_USER_DATA = "GET_USER_DATA"
const UPDATE_USER_DATA = "UPDATE_USER_DATA"
const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN"

const INVITE_FRIEND = "INVITE_FRIEND"
const DECLINE_FRIEND = "DECLINE_FRIEND"
const ACCEPT_FRIEND = "ACCEPT_FRIEND"
const REMOVE_FRIEND = "REMOVE_FRIEND"
const CANCEL_FRIEND = "CANCEL_FRIEND"

export {
    LOGIN,
    LOGOUT,
    GET_USER_DATA,
    UPDATE_USER_DATA,
    UPDATE_USER_LOGIN,
    
    INVITE_FRIEND,
    DECLINE_FRIEND,
    ACCEPT_FRIEND,
    REMOVE_FRIEND,
    CANCEL_FRIEND
}
