export default {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    GET_USER_DATA: "GET_USER_DATA",
    UPDATE_USER_DATA: "UPDATE_USER_DATA",
    UPDATE_USER_LOGIN: "UPDATE_USER_LOGIN",
    
    INVITE_FRIEND: "INVITE_FRIEND",
    DECLINE_FRIEND: "DECLINE_FRIEND",
    ACCEPT_FRIEND: "ACCEPT_FRIEND",
    REMOVE_FRIEND: "REMOVE_FRIEND",
    CANCEL_FRIEND: "CANCEL_FRIEND"
}
