const LOGGED_IN = "LOGGED_IN"
const FRIENDS_COMBINED = "FRIENDS_COMBINED"
const PRIVATE_WALL_POSTS = "PRIVATE_WALL_POSTS"
const PUBLIC_WALL_POSTS = "PUBLIC_WALL_POSTS"

const MAIN_WALL_POSTS_LAST = "MAIN_WALL_POSTS_LAST"

export {
    LOGGED_IN,
    FRIENDS_COMBINED,
    PRIVATE_WALL_POSTS,
    PUBLIC_WALL_POSTS,

    MAIN_WALL_POSTS_LAST
}
