const LOGGED_IN = "LOGGED_IN"
const FRIENDS_COMBINED = "FRIENDS_COMBINED"
const PRIVATE_WALL_POSTS = "PRIVATE_WALL_POSTS"
const PUBLIC_WALL_POSTS = "PUBLIC_WALL_POSTS"

export {
    LOGGED_IN,
    FRIENDS_COMBINED,
    PRIVATE_WALL_POSTS,
    PUBLIC_WALL_POSTS
}
