const SET_USER = "SET_USER"
const CLEAR_USER = "CLEAR_USER"
const UPDATE_USER = "UPDATE_USER"
const SET_USER_SOCKET = "SET_USER_SOCKET"
const ADD_COMMENT_TO_USER = "ADD_COMMENT_TO_USER"

const INVITES_SENT_ADD_USER = "INVITES_SENT_ADD_USER"
const INVITES_SENT_REMOVE_USER = "INVITES_SENT_REMOVE_USER"
const INVITES_RECEIVED_ADD_USER = "INVITES_RECEIVED_ADD_USER"
const INVITES_RECEIVED_REMOVE_USER = "INVITES_RECEIVED_REMOVE_USER"
const FRIENDS_ADD_USER = "FRIENDS_ADD_USER"
const FRIENDS_REMOVE_USER = "FRIENDS_REMOVE_USER"

const SET_CURRENT_POST = "SET_CURRENT_POST"
const CLEAR_CURRENT_POST = "CLEAR_CURRENT_POST"
const SET_CURRENT_POST_SOCKET = "SET_CURRENT_POST_SOCKET"
const ADD_COMMENT_TO_CURRENT_POST = "ADD_COMMENT_TO_CURRENT_POST"

export {
    SET_USER,
    CLEAR_USER,
    UPDATE_USER,
    SET_USER_SOCKET,
    ADD_COMMENT_TO_USER,

    INVITES_SENT_ADD_USER,
    INVITES_SENT_REMOVE_USER,
    INVITES_RECEIVED_ADD_USER,
    INVITES_RECEIVED_REMOVE_USER,
    FRIENDS_ADD_USER,
    FRIENDS_REMOVE_USER,
    
    SET_CURRENT_POST,
    CLEAR_CURRENT_POST,
    SET_CURRENT_POST_SOCKET,
    ADD_COMMENT_TO_CURRENT_POST
}
