const USER = "USER"
const USER_SOCKET = "USER_SOCKET"

const CURRENT_POST = "CURRENT_POST"
const CURRENT_POST_SOCKET = "CURRENT_POST_SOCKET"

export {
    USER,
    USER_SOCKET,
    
    CURRENT_POST,
    CURRENT_POST_SOCKET
}