const USER = "USER"
const USER_SOCKET = "USER_SOCKET"

const CURRENT_POST = "CURRENT_POST"
const CURRENT_POST_SOCKET = "CURRENT_POST_SOCKET"

const MAIN_WALL_POSTS = "MAIN_WALL_POSTS"
const MAIN_WALL_POSTS_SOCKETS = "MAIN_WALL_POSTS_SOCKETS"

export {
    USER,
    USER_SOCKET,
    
    CURRENT_POST,
    CURRENT_POST_SOCKET,
    
    MAIN_WALL_POSTS,
    MAIN_WALL_POSTS_SOCKETS
}